name: Selenium Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          maven-version: '3.1.0'

      - name: Install xmlstarlet
        run: sudo apt-get install -y xmlstarlet

      - name: Pull Selenium Docker image
        run: docker pull selenium/standalone-firefox:latest

      - name: Verify Docker image
        run: docker run --rm selenium/standalone-firefox:latest firefox --version

      - name: Build and Test with Maven
        run: mvn clean verify

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Upload Allure Report as artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: target/site/allure-maven-plugin

      - name: Display Surefire XML report
        if: always()
        run: |
          echo "Contents of Surefire XML report (testng-results.xml):"
          cat target/surefire-reports/testng-results.xml || echo "Surefire XML report not found."

      - name: Extract test results
        id: extract_results
        run: |
          total_tests=$(xmlstarlet sel -t -v "/testng-results/@total" target/surefire-reports/testng-results.xml)
          failed_tests=$(xmlstarlet sel -t -v "/testng-results/@failed" target/surefire-reports/testng-results.xml)
          skipped_tests=$(xmlstarlet sel -t -v "/testng-results/@skipped" target/surefire-reports/testng-results.xml)
          passed_tests=$(xmlstarlet sel -t -v "/testng-results/@passed" target/surefire-reports/testng-results.xml)
          echo "::set-output name=passed::$passed_tests"
          echo "::set-output name=failed::$failed_tests"
          echo "::set-output name=skipped::$skipped_tests"
          echo "::set-output name=total::$total_tests"

      - name: Display test results summary
        if: always()
        run: |
          echo "Total test cases = ${{ steps.extract_results.outputs.total }}"
          echo "Passed test cases = ${{ steps.extract_results.outputs.passed }}"
          echo "Failed test cases = ${{ steps.extract_results.outputs.failed }}"
